void main() {
//   double num = 23.523456;
//   print(num.truncate());
//   String singleLine = "This,is,single,line";
//   String multiLine = """This is
//   Multi
//   Line String
//   testing
//   system""";
//   String con =singleLine+multiLine;

//   print(singleLine);
//   print(multiLine);
  //print(con);
  //print("This is single : ${singleLine} and This is multiline : ${multiLine}");
  //print(singleLine.length);
  //print((singleLine.trim()).length);
//   print(singleLine.split(','));
//   print(singleLine.substring(0,7));
//   var test = 'abc';
//   if (test) {
//     print("This is a true value");
//   } else {
//     print("This is false value");
//   }
//   var fruits = new List(3);
//   fruits[0] ="Apple";
//   fruits[1] = "Bannan";
//   fruits[2] = " Fruits3";
//  var cars = ['Model1','Model2','Model3'];
//  //cars.add("Model4");
//   cars[1] = "model125";
//   print(cars);
  //print("This is model number : ${cars.last}");
//   var studentInfo = {'name':'Jhon','id':01235,'age':20,'Gender':'male'};
//   var studentInfo = new Map();
//   studentInfo['name'] = 'Jhon';
//   studentInfo['Id'] = 123;
//   //print(studentInfo['name']);
//   print(studentInfo.keys);

  message();

}
message(){
  print("We are learning dart");
}

